### ISSUE TITLE
In README.md: Checkboxes are no longer needed and actually break in Modrinth

### ISSUE THREAD

**Issue by James103** [SpaceServe/spaceserve-playtime#1]
As of commit e4474d241ca88055a62597546a1a670f5f6d3832, the [main description page](https://modrinth.com/mod/playtime) in Modrinth shows raw HTML describing the checkboxes instead of just bullet points. In other words, (using source code) what is currently as follows

```
 - [x] Track Playtime
     - [x] All playtime
     - [x] Improved afk detection
     - [x] Afk time
     - [x] Non-afk playtime
     - [x] The above, but dimension specific
 - [x] Playtime Triggers and Events
     - [x] Playtime event on afk and on active
     - [x] All playtime types as advancement triggers
     - [x] All playtime types as scoreboard objectives 
 - [x] Simple playtime to Duration conversion
```

should become:
```
 - Track Playtime
     - All playtime
     - Improved afk detection
     - Afk time
     - Non-afk playtime
     - The above, but dimension specific
 - Playtime Triggers and Events
     - Playtime event on afk and on active
     - All playtime types as advancement triggers
     - All playtime types as scoreboard objectives 
 - Simple playtime to Duration conversion
```

**Comment by spaceclouds42** [comment]
I suppose I should fix that shouldn't I. I've already reported the bug to modrinth [here](https://github.com/modrinth/code/issues/1982), and it's fixed in a currently open PR so it hopefully won't be an issue for long.

**Comment by triphora** [comment]
> it's fixed in a currently open PR so it hopefully won't be an issue for long.

~~This fix finally got pushed to production btw :P~~
Got reverted to v0.1.3 :P
